import React, { useState } from 'react';
import Image from 'next/image';
import Share from './share';
import Stats from './stats';
import { useRouter } from 'next/router';

const Header = () => {
  const router = useRouter();

  const [isAboutDialogOpen, setAboutDialogOpen] = useState(false);
  const [isStatDialogOpen, setStatDialogOpen] = useState(false);
  const [isShareDialogOpen, setShareDialogOpen] = useState(false);

  const refreshPage = () => {
    router.replace(router.asPath);
  };

  const handleAboutOpenDialog = () => {
    setAboutDialogOpen(true);
  };

  const handleAboutCloseDialog = () => {
    setAboutDialogOpen(false);
  };

  const handleStatOpenDialog = () => {
    setStatDialogOpen(true);
  };

  const handleStatCloseDialog = () => {
    setStatDialogOpen(false);
  };

  const handleShareOpenDialog = () => {
    setShareDialogOpen(true);
  };

  const handleShareCloseDialog = () => {
    setShareDialogOpen(false);
  };

  return (
    <header className="flex items-center justify-between p-2 bg-gray-200">
      <div className="items-center">
        <a href="/" onClick={refreshPage}>
          <img src="logo.png" alt="Logo" className="w-12 h-12 mr-2" />
        </a>
      </div>
      <div className="items-center">
        <div className="flex flex-grow text-center	justify-center w-auto">
          <a href="/" onClick={refreshPage}>
            <h1 className="text-2xl font-bold ">Real vs AI</h1>
          </a>
        </div>
      </div>
      <div className="flex items-end">
        <a
          href="#"
          onClick={handleAboutOpenDialog}
          className="text-blue-500 hover:underline cursor-pointer mr-2"
        >
          <Image priority src="info.svg" height={32} width={32} alt="Info" />
        </a>
        <a
          href="#"
          onClick={handleStatOpenDialog}
          className="text-blue-500 hover:underline cursor-pointer mr-2"
        >
          <Image priority src="rank.svg" height={32} width={32} alt="Stat" />
        </a>
        <Image
          priority
          src="share.svg"
          height={32}
          width={32}
          alt="Stat"
          onClick={handleShareOpenDialog}
          className="text-blue-500 hover:underline cursor-pointer mr-2"
        />
      </div>
      {isAboutDialogOpen && (
        <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-75">
          <div className="bg-white p-4">
            <div className="flex flex-grow text-center	justify-center w-auto divide-y">
              <h2 className="text-lg font-bold mb-2 border-b">How To Play</h2>
            </div>
            <h3 className="font-semibold mb-2">
              Guess the Real or Human Created image in each Round.
            </h3>
            <p className="w-96">
              Unique experience where you'll be presented with two images and
              asked to identify which one is created by a human and which one is
              generated by a machine.
            </p>
            <p className=" pt-2">
              <a
                href="https://en.wikipedia.org/wiki/Turing_test"
                target="_blank"
              >
                Turing Test
                <Image
                  priority
                  src="external.svg"
                  height={16}
                  width={16}
                  alt="external"
                  className="inline"
                />
              </a>
            </p>

            <p className="w-96 mt-2 italic">
              Can you outsmart the latest advancements in artificial
              intelligence?
            </p>
            <button
              onClick={handleAboutCloseDialog}
              className="mt-4 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 float-right"
            >
              Close
            </button>
          </div>
        </div>
      )}

      {isStatDialogOpen && <Stats onCloseStats={handleStatCloseDialog} />}
      {isShareDialogOpen && <Share onCloseShare={handleShareCloseDialog} />}
    </header>
  );
};

export default Header;
