import React, { useState } from 'react';

const Header = () => {
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const handleOpenDialog = () => {
    setIsDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setIsDialogOpen(false);
  };

  return (
    <header className="flex items-center justify-between p-4">
      <div className="flex items-center">
        <img
          src="logo.png"
          alt="Logo"
          className="w-12 h-12 mr-2"
        />
        <h1 className="text-2xl font-bold">Human vs AI</h1>
      </div>
      <a
        href="#"
        onClick={handleOpenDialog}
        className="text-blue-500 hover:underline cursor-pointer"
      >
        About Us
      </a>

      {isDialogOpen && (
        <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-75">
          <div className="bg-white p-4">
            <h2 className="text-lg font-bold mb-2">About Us</h2>
            <p>
            unique experience where you'll be presented with two images and asked to identify which one is created by a human and which one is generated by a machine. Can you outsmart the latest advancements in artificial intelligence?
            </p>
            <button
              onClick={handleCloseDialog}
              className="mt-4 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </header>
  );
};

export default Header;
